# Generated by Django 4.1.5 on 2023-01-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content_Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Meta_Title', models.CharField(max_length=50)),
                ('Meta_Description', models.TextField()),
                ('Headings', models.TextField()),
                ('Google_Preview', models.CharField(max_length=50)),
                ('Keyword_Density', models.PositiveIntegerField(max_length=50)),
                ('Image_Alt_Check', models.PositiveIntegerField(max_length=50)),
                ('Links', models.PositiveIntegerField(max_length=50)),
                ('Status_Code', models.CharField(max_length=50)),
                ('Verdict', models.CharField(max_length=50)),
            ],
        ),
    ]
