# Generated by Django 3.1 on 2023-01-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SEOAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content_analysis',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
