# Generated by Django 3.1 on 2023-01-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SEOAnalyzer', '0002_auto_20230112_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content_analysis',
            name='Google_Preview',
        ),
        migrations.RemoveField(
            model_name='content_analysis',
            name='Headings',
        ),
        migrations.RemoveField(
            model_name='content_analysis',
            name='Image_Alt_Check',
        ),
        migrations.RemoveField(
            model_name='content_analysis',
            name='Keyword_Density',
        ),
        migrations.RemoveField(
            model_name='content_analysis',
            name='Links',
        ),
        migrations.RemoveField(
            model_name='content_analysis',
            name='Meta_Description',
        ),
        migrations.RemoveField(
            model_name='content_analysis',
            name='Status_Code',
        ),
        migrations.RemoveField(
            model_name='content_analysis',
            name='Verdict',
        ),
    ]
