# Generated by Django 4.2 on 2023-04-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SEOAnalyzer', '0004_auto_20230127_0006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
